Feature/save and load analysis
ManiVaultStudio/core pull request #457
Opened 2024-01-15 17:11 UTC by alxvth

This PR supersedes #455.
All existing plugins should still just compile and run fine with after PR.

ManiVault can now save and load analysis plugins to/from projects files.

Analysis plugins now can have multiple Input and Output datasets:
```cpp
// Analysis & Transformation and Writer Plugins
void setInputDataset(const Dataset<DatasetImpl>& inputDataset);
void setInputDatasets(const Datasets& inputDatasets);               // NEW

Dataset<DatasetType> getInputDataset();
Datasets getInputDatasets();                                        // NEW

// Only Analysis Plugins
void setOutputDataset(const Dataset<DatasetImpl>& outputDataset);
void setOutputDatasets(const Datasets& outputDatasets);             // NEW

Dataset<DatasetType> getOutputDataset();
Datasets getOutputDatasets();                                       // NEW

bool outputDataInit()                                               // NEW
```

Your Analysis plugin must of course overload the `fromVariantMap` and `toVariantMap` functions. Additionally, the `init()` function needs to take into account that the out dataset of the plugin will already be loaded and does not need to be created anymore.
Here is an example setup when implementing save-able analysis plugins:
```cpp
// if not loaded from project, init new data
if (!outputDataInit())
{
    qDebug() << "PCAPlugin::create new derived data";

    auto newOutput = Dataset<Points>(mv::data().createDerivedDataset("PCA", inputDataset, inputDataset));
    setOutputDataset(newOutput);

    // Set initial data (default 2 dimensions, all points at (0,0) )
    std::vector<float> initialData;
    const size_t numInitialDataDimensions = 2;
    const auto numPoints = inputDataset->getNumPoints();
    initialData.resize(numInitialDataDimensions * numPoints);
    newOutput->setData(initialData.data(), numPoints, numInitialDataDimensions);
    events().notifyDatasetDataChanged(newOutput);
}

// Same as always
auto outputDataset = getOutputDataset<Points>();
```

2024-01-18 15:49 UTC, alxvth commented
`Plugin::getVersion()` returns now the version string set in the meta data in the `plugin.json` file

2024-01-18 16:02 UTC, alxvth commented
This PR also addresses #200 with 
```cpp
    if (variantMap.contains("GroupIndex") && variantMap["GroupIndex"].toInt() >= 0)
        setGroupIndex(variantMap["GroupIndex"].toInt());
```
See [here](https://github.com/ManiVaultStudio/core/pull/457/files#diff-d247288e68d47c768da7460b26a995560fde016f594363160e8fa67de0de66baR165)

2024-01-19 10:38 UTC, ThomasKroes requested changes
I only have five small comments (see in the PR conversation) :)

I will test this PR in concert with the [SNE PR](https://github.com/ManiVaultStudio/t-SNE-Analysis/pull/88) ASAP!

2024-01-19 10:38 UTC, ThomasKroes commented on HDPS/src/AnalysisPlugin.h
> +     * Load view plugin from variant
Very minor:
`Load analysis plugin from variant`
`@param Variant representation of the analysis plugin`

2024-01-19 10:38 UTC, ThomasKroes commented on HDPS/src/AnalysisPlugin.h
> +     * Save view plugin to variant
Very minor:
`Save analysis plugin to variant`
`@param Variant representation of the analysis plugin`

2024-01-19 10:38 UTC, ThomasKroes commented on HDPS/src/Set.cpp
> +        { "SourceDatasetGUID", isDerivedData() ? QVariant::fromValue(_sourceDataset->getId()) : "" },
Minor: for consistency with other parts of the Core source code I would propose using the `ID` instead of `GUID`

2024-01-19 10:38 UTC, ThomasKroes commented on HDPS/src/Set.cpp
> +        { "FullDatasetGUID", isFull() ? "" : QVariant::fromValue(_fullDataset->getId()) },
Same as above

2024-01-19 10:38 UTC, ThomasKroes commented on HDPS/src/AnalysisPlugin.cpp
> +    variantMap["InputDatasetsGUIDs"] = inputDatasetsGUIDs;
Minor also; perhaps here we can also use `ID` instead of `GUID`?

2024-01-19 11:51 UTC, alxvth commented on HDPS/src/AnalysisPlugin.h
> +     * Load view plugin from variant
Ah yes, that was some left-over copy-paste...

2024-01-19 11:56 UTC, alxvth commented on HDPS/src/Set.cpp
> +        { "SourceDatasetGUID", isDerivedData() ? QVariant::fromValue(_sourceDataset->getId()) : "" },
I changed all GUIDs to IDs

2024-01-19 12:41 UTC, merged